/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import entities.Comentario;
import entities.Filme;
import entities.Genero;
import java.awt.event.ItemEvent;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import repository.Repository;

/**
 *
 * @author jorgehenriquechiarelli
 */
public class ComentarioForm extends javax.swing.JDialog {
    private boolean regNew = false;
    private LinkedList<Comentario> listComentario = new LinkedList<>();
    private LinkedList<Filme> listFilme = new LinkedList<>();
    private Repository repository = new Repository();

    /**
     * Creates new form ComentarioForm
     */
    public ComentarioForm() {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        btNovoActionPerformed(null);
        listComentario.addAll(repository.listComentarios());
        cbComentarios.setModel(new DefaultComboBoxModel(listComentario.toArray()));
        cbComentarios.setSelectedIndex(-1);
        listFilme.addAll(repository.listFilmes());
        cbFilmes.setModel(new DefaultComboBoxModel(listFilme.toArray()));                
        cbFilmes.setSelectedIndex(-1);
        
    }
    
     private void limpaCampos() {
        cbFilmes.setSelectedIndex(-1);
        cbComentarios.setSelectedIndex(-1);
        tfNota.setText("");
        tfUsuario.setText("");
        tfComentario.setText("");
    }
    
    private boolean checkFieldEmpty () {
        String textComentarios = tfComentario.getText();     
        String textNota = tfNota.getText();
        String textUsuario = tfNota.getText();
        
        if (cbFilmes.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Filme", "Atenção", JOptionPane.WARNING_MESSAGE);            
            return true;
        }
        
        if (textComentarios.length() < 1) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Comentário", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        
        if (textNota.length() < 1) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Nota", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        
        if (textUsuario.length() < 1) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Usuário", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        
               
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNota = new javax.swing.JTextField();
        tfUsuario = new javax.swing.JTextField();
        tfComentario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbComentarios = new javax.swing.JComboBox();
        cbFilmes = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("Usuário:");

        jLabel5.setText("Comentário:");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Comentários");

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel7.setText("Comentários: ");

        jLabel3.setText("Nota:");

        cbComentarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbComentariosItemStateChanged(evt);
            }
        });

        cbFilmes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFilmesItemStateChanged(evt);
            }
        });

        jLabel2.setText("Selecione o Filme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfComentario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNota, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 49, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbComentarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbFilmes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btSalvar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        regNew = true;
        btSalvar.setEnabled(true);
        btNovo.setEnabled(false);
        limpaCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (checkFieldEmpty()) return ;

        Comentario comentario = null;
        Filme filme = null;

        if (regNew) {
            comentario = new Comentario();
        } else {
            comentario = (Comentario) cbComentarios.getSelectedItem();
        }

        filme = (Filme) cbFilmes.getSelectedItem();

        comentario.setNota(Double.parseDouble(tfNota.getText()));
        comentario.setUsuario(tfUsuario.getText());
        comentario.setComentario(tfComentario.getText());
        comentario.setFilme(filme.getIdFilme());

        if (regNew) {
            cbComentarios.addItem(comentario);
            listComentario.add(comentario);
            repository.addComentario(comentario);
        } else {
            repository.updateComentario(comentario);
        }

        btNovo.setEnabled(true);
        btSalvar.setEnabled(false);
        btNovoActionPerformed(null);
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void cbComentariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbComentariosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Comentario comentario = (Comentario) cbComentarios.getSelectedItem();

            tfNota.setText(comentario.getNota().toString());
            tfUsuario.setText(comentario.getUsuario());
            tfComentario.setText(comentario.getComentario());

            Filme filme = repository.findFilme(comentario.getFilme());

            if (filme != null) {
                cbFilmes.getModel().setSelectedItem(filme);
                for (int i = 0; i < cbFilmes.getModel().getSize(); i++) {                    
                    final String txt = filme.getIdFilme()+ " - " + filme.getTitulo();
                    if (cbFilmes.getModel().getElementAt(i).toString().equals(txt)) {
                        cbFilmes.setSelectedIndex(i);
                    }
                }   
            }

            btSalvar.setEnabled(true);
            btNovo.setEnabled(true);

            regNew = false;
        }
    }//GEN-LAST:event_cbComentariosItemStateChanged

    private void cbFilmesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFilmesItemStateChanged

    }//GEN-LAST:event_cbFilmesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComentarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComentarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComentarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComentarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComentarioForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbComentarios;
    private javax.swing.JComboBox cbFilmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfComentario;
    private javax.swing.JTextField tfNota;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
