/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import entities.Filme;
import entities.Genero;
import java.awt.event.ItemEvent;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import repository.Repository;

/**
 *
 * @author jorgehenriquechiarelli
 */
public class FilmeForm extends javax.swing.JDialog {
    private boolean regNew = false;
    private LinkedList<Genero> listGenero = new LinkedList<>();
    private LinkedList<Filme> listFilme = new LinkedList<>();
    private Repository repository = new Repository();


    /**
     * Creates new form FilmeForm
     */
    public FilmeForm() {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        btNovoActionPerformed(null);
        listFilme.addAll(repository.listFilmes());
        cbFilmes.setModel(new DefaultComboBoxModel(listFilme.toArray()));        
        listGenero.addAll(repository.listGeneros());
        cbFilmes.setSelectedIndex(-1);
        cbGeneros.setModel(new DefaultComboBoxModel(listGenero.toArray()));
        cbGeneros.setSelectedIndex(-1);
    }
    
    private void limpaCampos() {
        cbFilmes.setSelectedIndex(-1);
        cbGeneros.setSelectedIndex(-1);
        tfTitulo.setText("");
        tfAno.setText("");
        tfDiretor.setText("");
        tfPais.setText("");
    }
    
    private boolean checkFieldEmpty () {
        String textTitulo = tfTitulo.getText();  
        String textAno = tfAno.getText();
        String textDiretor = tfDiretor.getText();
        String textPais = tfPais.getText();
        
        if (cbGeneros.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Genero", "Atenção", JOptionPane.WARNING_MESSAGE);            
            return true;
        }
        
        if (textTitulo.length() < 1) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Título", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        
        if (textAno.length() < 1) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Ano", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        
        if (textDiretor.length() < 1) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Diretor", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        
        if (textPais.length() < 1) {
            JOptionPane.showMessageDialog(this, "Preencha o campo País", "Atenção", JOptionPane.WARNING_MESSAGE);
            return true;
        }        
               
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbGeneros = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        tfAno = new javax.swing.JTextField();
        tfDiretor = new javax.swing.JTextField();
        tfPais = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbFilmes = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Filmes");

        jLabel2.setText("Selecione o Genero");

        cbGeneros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGenerosItemStateChanged(evt);
            }
        });

        jLabel3.setText("Título:");

        jLabel4.setText("Ano:");

        jLabel5.setText("Diretor:");

        jLabel6.setText("País:");

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel7.setText("Filmes: ");

        cbFilmes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFilmesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGeneros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTitulo)
                                    .addComponent(tfDiretor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 127, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFilmes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDiretor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btSalvar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGenerosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGenerosItemStateChanged
        
    }//GEN-LAST:event_cbGenerosItemStateChanged

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        regNew = true;
        btSalvar.setEnabled(true);
        btNovo.setEnabled(false);
        limpaCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (checkFieldEmpty()) return ;

        Filme filme = null;
        Genero genero = null;

        if (regNew) {
            filme = new Filme();
        } else {
            filme = (Filme) cbFilmes.getSelectedItem();
        }
        
        genero = (Genero) cbGeneros.getSelectedItem();
        
        filme.setTitulo(tfTitulo.getText());
        filme.setAno(tfAno.getText());
        filme.setDiretor(tfDiretor.getText());
        filme.setPais(tfPais.getText());        
        filme.setGenero(genero.getIdGenero());                

        if (regNew) {
            cbFilmes.addItem(filme);
            listFilme.add(filme);
            repository.addFilme(filme);
        } else {
            repository.updateFilme(filme);
        }

        

        btNovo.setEnabled(true);
        btSalvar.setEnabled(false);
        btNovoActionPerformed(null);
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void cbFilmesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFilmesItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Filme filme = (Filme) cbFilmes.getSelectedItem();
            
            tfTitulo.setText(filme.getTitulo());
            tfAno.setText(filme.getAno());
            tfDiretor.setText(filme.getDiretor());
            tfPais.setText(filme.getPais());
            
            Genero genero = repository.findGenero(filme.getGenero());
            
            if (genero != null) {
                cbGeneros.getModel().setSelectedItem(genero);
                for (int i = 0; i < cbGeneros.getModel().getSize(); i++) {                    
                    final String txt = genero.getIdGenero() + " - " + genero.getDescricao();
                    if (cbGeneros.getModel().getElementAt(i).toString().equals(txt)) {
                        cbGeneros.setSelectedIndex(i);
                    }
                }        
            }
            
            btSalvar.setEnabled(true);
            btNovo.setEnabled(true);
            
            regNew = false;
        }
    }//GEN-LAST:event_cbFilmesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbFilmes;
    private javax.swing.JComboBox cbGeneros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfDiretor;
    private javax.swing.JTextField tfPais;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
